#!/bin/bash

var1=$1;
var2=$2;
var3=$3;



if [ "$var1" == "1" ]; then

    for ((i=1;i < var2; i++ ));
    do

      for (( j = var2-1; j >= i; j-- ));
      do
        echo -ne " ";
      done
      for (( k = 1; k <=i; k++ ));
       do
        echo -ne " *";
      done
      echo;
    done
    for (( q = 0; q < var3; q++ )); do
      echo  -ne " ";
    done
         echo " | |"
    for (( w = 0; w < var3; w++ )); do
      echo  -ne " ";
    done
       echo "_|_|_"


fi
