#!/bin/bash
#
# Notes is a shell script that allows the user to create notes directly
# in the terminal. It will automatically add the creation date to any new
# note

NAME=$1
LOCATION=$2
NOTE=$3

if [ "$NAME" == "-d" ]; then
    NAME=`date +"%Y-%m-%d"`
else
    NAME=$1
fi

cd $LOCATION

# create or append new content to a file
if [ ! -f $PWD'/'$NAME ]; then
	printf "Creating new file in $PWD \n"
	touch $NAME                                 # create the file
    printf "\n" >> $NAME                            # insert newline to the file
    echo "NOTE CREATED: " `date +"%T"` >> $NAME # insert current time
	printf "$NOTE\n" >> $NAME                                # insert text
	cat $NAME                                   # printout current content
else
	printf "Appending to existing file in $PWD\nThe file contains the following text so far ...\n"
    printf "\n" >> $NAME                            # insert newline to the file
    echo "NOTE CREATED: " `date +"%T"` >> $NAME # insert current time
	printf "$NOTE\n" >> $NAME                               # insert text
	cat $NAME                                   # printout current content
fi

cd $OLDPWD
