#!/bin/bash
#
# Notes is a shell script that allows the user to create notes directly
# in the terminal. It will automatically add the creation date to any new
# note

NAME=$1
LOCATION=$2
NOTE=$3

# check if NAME isn't empty, if so, save current date to it
#if [ -z "$NAME" ]; then
#	NAME=`date +"%Y-%m-%d"`

# or if the "-d" is specified, save current date to it
#elif [ $NAME="-d" ]; then
#	NAME=`date +"%Y-%m-%d"`

# otherwise use the name specified by the user
#if [ $NAME="-d" ]; then
#    NAME=`date +"%Y-%m-%d"`
#else
#	NAME=$1
#fi

# check if LOCATION has been specified, if not, current directory path is used
#if [ -z "$LOCATION" ]; then
#	LOCATION=$PWD

# otherwise use user specified path
#else
#	LOCATION=$2
#fi

cd $LOCATION

# create or append new content to a file
if [ ! -f $PWD'/'$NAME ]; then
	echo "Creating new file in $PWD"
	echo ""                                     # just a visual newline
	touch $NAME                                 # create the file
    echo "" >> $NAME                            # insert newline to the file
    echo "NOTE CREATED: " `date +"%T"` >> $NAME # insert current time
	echo $NOTE >> $NAME                                # insert text
	cat $NAME                                   # printout current content
else
	echo "Appending to existing file in $PWD, the file contains the following text so far ..."
	echo ""
	echo ""                                     # insert newline
    echo "" >> $NAME                            # insert newline to the file
    echo "NOTE CREATED: " `date +"%T"` >> $NAME # insert current time
	echo $NOTE >> $NAME                                # insert text
	cat $NAME                                   # printout current content
fi

cd $OLDPWD
