#!/usr/bin/env bash

# Name: Tomasz Klebek
# Discription: Converts plan text chmod to numbers and vice versa
# Date: 2018-11-13


VAR=($1 $2 $3);
VAR1=RWX;
VAR2=RWX;
VAR3=RWX;


for item in ${VAR[*]};
do
  if  ([ "$item" == "7" ] || [ "$item" == "rwx" ]); then
    if [ "$item" == "7" ]; then
      echo -n "rwx";
    elif [ "$item" = "rwx" ]; then
      echo -n "7";
    fi
 elif ([ "$item" == "6" ] || [ "$item" == "rw-" ]); then
   if [ "$item" == "6" ]; then
     echo -n "rw-";
   elif [ "$item" == "rw-" ]; then
     echo -n "6";
   fi
 elif ([ "$item" == "5" ] || [ "$item" == "r-x" ]); then
   if [ "$item" == "5" ]; then
     echo -n "r-x";
   elif [ "$item" == "r-x" ]; then
     echo -n "5";
   fi
 elif ([ "$item" == "4" ] || [ "$item" == "r--" ]); then
   if [ "$item" == "4" ]; then
     echo -n "r--";
   elif [ "$item" == "r--" ]; then
     echo -n "4";
   fi
 elif ([ "$item" == "3" ] || [ "$item" == "-wx" ]); then
   if [ "$item" == "3" ]; then
     echo -n "-wx";
   elif [ "$item" == "-wx" ]; then
     echo -n "3";
   fi
 elif ([ "$item" == "2" ] || [ "$item" == "-w-" ]); then
   if [ "$item" == "2" ]; then
     echo -n "-w-";
   elif [ "$item" == "-w-" ]; then
     echo -n "2";
   fi
 elif ([ "$item" == "1" ] || [ "$item" == "--x" ]); then
   if [ "$item" == "1" ]; then
     echo -n "--x";
   elif [ "$item" == "--x" ]; then
     echo -n "1";
   fi
 elif ([ "$item" == "0" ] || [ "$item" == "---" ]); then
   if [ "$item" == "0" ]; then
     echo -n "---";
   elif [ "$item" == "---" ]; then
     echo -n "0";
   fi
  fi

done
echo ""
