#!/bin/bash
# creates a number of empty dummy test files based on specified name, extension
# and location, if no location is specified, files are created in the current directory
#
# Usage
#
# tf [NUMBER_OF_FILES_TO_CREATE]... [PATH]...
#
####################################################################################

NUMBER_OF_FILES_TO_CREATE=$1
LOCATION=$2
FILE_NAME=$3
EXTENSION=$4
PROOF=$5
POPULATE=$6
SIZE=$7

# if -p is passed instead of a path, files are created in current directory
if [[ $2 == -p ]]; then
	LOCATION=${PWD}
# otherwise they are created in specified directory
else
    LOCATION=$2
fi

cd $LOCATION

# create the dummy files
for i in $(seq 1 $1)
	do
        if [[ $POPULATE == -x ]]; then
            < /dev/urandom tr -dc "[:alnum:]" | head -c$SIZE > $FILE_NAME$i'.'$EXTENSION
        else
            touch $FILE_NAME$i'.'$EXTENSION
        fi
	done

# print tree directory structure where files were created
#tree
if [[ $5 == -t ]]; then
    tree
fi

# return to the directory this command was invoked from
cd $OLDPWD

echo "$1 files created in $LOCATION"
