#!/bin/bash
# creates a number of empty dummy test files based on specified name, extension
# and location, if no location is specified, files are created in the current directory
#
# Usage
#
# tf [NUMBER_OF_FILES_TO_CREATE]... [PATH]...
#
####################################################################################

NUMBER_OF_FILES_TO_CREATE=$1
LOCATION=$2
FILE_NAME=$3
EXTENSION=$4

# if -p is passed instead of a path, files are created in current directory
if [[ $2 == -p ]]; then
	LOCATION=${PWD}
# otherwise they are created in specified directory
else
    LOCATION=$2
fi

cd $LOCATION

# create the dummy files
for i in $(seq 1 $1)
	do
		touch $FILE_NAME$i'.'$EXTENSION
	done

# print tree directory structure where files were created
tree

# return to the directory this command was invoked from
cd $OLDPWD

echo "$1 files created in $LOCATION"
