#!/bin/sh
# creates a number of empty dummy test files based on specified name, extension
# and location, if no location is specified, files are created in the current directory
#
# Usage
#
# tf [NUMBER_OF_FILES_TO_CREATE]... [PATH]...
#
####################################################################################

NUMBER_OF_FILES_TO_CREATE=$1
LOCATION=$2
FILE_NAME=$3
EXTENSION=$4

# check if a PATH parameter was invoked, if not, assign location
# of creation of the files to current directory
if [ -n "$LOCATION" ]; then
	LOCATION=$2

# otherwise use specified location
elif [ -z "$LOCATION" ]; then
	LOCATION=${PWD}
fi

cd $LOCATION

# create the dummy files
for i in $(seq 1 $1)
	do
		touch $FILE_NAME$i'.'$EXTENSION
	done

# return to the directory this command was invoked from
cd $OLDPWD

echo "$1 files created in $LOCATION"
