#!/usr/bin/env bash

while [ ! $# -eq 0 ]
do
	case "$1" in
		--help | -h)
			echo helpmenu
			exit
			;;
		--take-over-world | -t)
			echo secretopt
			exit
			;;
    --ok | -o)
			echo "your ok "
			exit
			;;
    tom | -w)
			echo Tom
			exit
			;;
	esac
	shift
done
