#!/usr/bin/env bash

# Name: Tomasz Klebek
# Discription: Converts letters to a number between 0 and 25
# depending on ther position in the alphabet
# Date: 2018-11-19

alph=(a b c d e f g h i j k l m n o p q r s t u v w x y z )

strNum=0
keyNum=0
cypherNum=0

string=$2
key=$1


#-----------------------STRING------------------------------
  read -a SARRAY <<< $(echo "$string" | sed 's/./& /g')

   j=0
   w=0
   i=0
   n=0

  while [ "${#strNum[@]}" -lt "${#SARRAY[@]}" ]; do

    if [[ "${SARRAY[$w]}" != "${alph[$j]}" ]]; then
      # echo "j=$j"
      # echo "w=$w"
      # echo "alph=${alph[$j]}"
      # echo "SARRAY=${SARRAY[$w]}"
      # echo =================================
      j=$((j+1))

      if [ "$j" -gt 25 ]; then
        j=0
      fi

    elif [[ "${SARRAY[$w]}" == "${alph[$j]}" ]]; then
      # echo +++++++++++++++++
      # echo "w=$w"
      w=$((w+1))
      # echo "w=$w"
      # echo "n=$n"
      strNum[n]="$j"
      n=$((n+1))
      j=0
    fi

  done

#-----------------------KEY------------------------------
  read -a KARRAY <<< $(echo "$key" | sed 's/./& /g')

   j=0
   w=0

   i=0
   n=0

  while [ "${#keyNum[@]}" -lt "${#KARRAY[@]}" ]; do

    if [[ "${KARRAY[$w]}" != "${alph[$j]}" ]]; then
      # echo "j=$j"
      # echo "w=$w"
      # echo "alph=${alph[$j]}"
      # echo "SARRAY=${SARRAY[$w]}"
      # echo =================================
      j=$((j+1))

      if [ "$j" -gt 25 ]; then
        j=0
      fi

    elif [[ "${KARRAY[$w]}" == "${alph[$j]}" ]]; then
      # echo +++++++++++++++++
      # echo "w=$w"
      w=$((w+1))
      # echo "w=$w"
      # echo "n=$n"
      keyNum[n]="$j"
      n=$((n+1))
      j=0
    fi
  done

echo "${keyNum[@]}"
for each in ${keyNum[@]}; do
  echo -ne "${alph[$each]}"
done
echo ""

echo "${strNum[@]}"
for each in ${strNum[@]}; do
  echo -ne "${alph[$each]}"
done
echo ""

for ((q=0;q < "${#strNum[@]}";q++)); do
  cypherNum[$q]=$(( ${strNum[$q]}+${keyNum[$q]} ))
  # echo q-1=$(($q-1))
  # echo q=$q
  # echo ${#keyNum[@]}
  # echo ++++++++++++
  # if [[ "$q" == "${#keyNum[@]}" ]]; then
  #   echo "ife
  #   q=0
  # fi
done

echo "${cypherNum[@]}"
